/*
 *  Copyright 2008 The Apache Software Foundation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.zzg.mybatis.generator.plugins;

import static org.mybatis.generator.internal.util.StringUtility.isTrue;

import java.util.Optional;
import java.util.Properties;
import java.util.Set;

import org.mybatis.generator.api.CommentGenerator;
import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.java.CompilationUnit;
import org.mybatis.generator.api.dom.java.Field;
import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType;
import org.mybatis.generator.api.dom.java.InnerClass;
import org.mybatis.generator.api.dom.java.InnerEnum;
import org.mybatis.generator.api.dom.java.Method;
import org.mybatis.generator.api.dom.java.TopLevelClass;
import org.mybatis.generator.api.dom.xml.TextElement;
import org.mybatis.generator.api.dom.xml.XmlElement;
import org.mybatis.generator.config.GeneratedKey;
import org.mybatis.generator.internal.util.StringUtility;

/**
 * 此插件使用数据库表中列的注释来生成Java Model中属性的注释
 *
 * @author Owen Zou
 *
 */
public class DbRemarksCommentGenerator implements CommentGenerator {

    private Properties properties;
    private boolean columnRemarks;
    private boolean isAnnotations;

    public DbRemarksCommentGenerator() {
        super();
        properties = new Properties();
    }

    @Override
    public void addJavaFileComment(CompilationUnit compilationUnit) {
        // add no file level comments by default
        if (isAnnotations) {
            compilationUnit.addImportedType(new FullyQualifiedJavaType("javax.persistence.Table"));
            compilationUnit.addImportedType(new FullyQualifiedJavaType("javax.persistence.Id"));
            compilationUnit.addImportedType(new FullyQualifiedJavaType("javax.persistence.Column"));
            compilationUnit.addImportedType(new FullyQualifiedJavaType("javax.persistence.GeneratedValue"));
            compilationUnit.addImportedType(new FullyQualifiedJavaType("org.hibernate.validator.constraints.NotEmpty"));
        }
    }

    /**
     * Adds a suitable comment to warn users that the element was generated, and
     * when it was generated.
     */
    @Override
    public void addComment(XmlElement xmlElement) {
        if (!columnRemarks) {
            xmlElement.addElement(new TextElement("<!--")); //$NON-NLS-1$

            StringBuilder sb = new StringBuilder();
            sb.append("  WARNING - @mbggenerated"); //$NON-NLS-1$
            xmlElement.addElement(new TextElement(sb.toString()));
            xmlElement.addElement(new TextElement("  This element is automatically generated by MyBatis Generator," //$NON-NLS-1$
                    + " do not modify.")); //$NON-NLS-1$

            xmlElement.addElement(new TextElement("-->")); //$NON-NLS-1$
        }
    }

    @Override
    public void addRootComment(XmlElement rootElement) {
        // add no document level comments by default
        return;
    }

    @Override
    public void addGeneralMethodAnnotation(Method method, IntrospectedTable introspectedTable, Set<FullyQualifiedJavaType> set) {

    }

    @Override
    public void addGeneralMethodAnnotation(Method method, IntrospectedTable introspectedTable, IntrospectedColumn introspectedColumn, Set<FullyQualifiedJavaType> set) {

    }

    @Override
    public void addFieldAnnotation(Field field, IntrospectedTable introspectedTable, Set<FullyQualifiedJavaType> set) {

    }

    @Override
    public void addFieldAnnotation(Field field, IntrospectedTable introspectedTable, IntrospectedColumn introspectedColumn, Set<FullyQualifiedJavaType> set) {

    }

    @Override
    public void addClassAnnotation(InnerClass innerClass, IntrospectedTable introspectedTable, Set<FullyQualifiedJavaType> set) {
    }

    @Override
    public void addConfigurationProperties(Properties properties) {
        this.properties.putAll(properties);
        columnRemarks = isTrue(properties.getProperty("columnRemarks"));
        isAnnotations = isTrue(properties.getProperty("annotations"));
    }

    @Override
    public void addClassComment(InnerClass innerClass, IntrospectedTable introspectedTable) {
        if (!columnRemarks) {
            innerClass.addJavaDocLine("/**");
            innerClass.addJavaDocLine(" * This class was generated by MyBatis Generator.");
            innerClass.addJavaDocLine(" * This class corresponds to the database table " + introspectedTable.getTableConfiguration().getTableName());
            innerClass.addJavaDocLine(" *");
            innerClass.addJavaDocLine(" * @mbggenerated");
            innerClass.addJavaDocLine(" */");
        }
    }

    /**
     * 实体类注释.
     */
    @Override
    public void addModelClassComment(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        topLevelClass.addJavaDocLine("/**");
        topLevelClass.addJavaDocLine(" * " + introspectedTable.getRemarks());
        topLevelClass.addJavaDocLine(" * @author ");
        topLevelClass.addJavaDocLine(" */");
        if (isAnnotations) {
            topLevelClass.addAnnotation("@Table(name=\"" + introspectedTable.getFullyQualifiedTableNameAtRuntime() + "\")");
        }
    }

    @Override
    public void addEnumComment(InnerEnum innerEnum, IntrospectedTable introspectedTable) {
    }

    @Override
    public void addFieldComment(Field field, IntrospectedTable introspectedTable, IntrospectedColumn introspectedColumn) {
        if (columnRemarks) {
            if (StringUtility.stringHasValue(introspectedColumn.getRemarks())) {
                field.addJavaDocLine("/**");
                field.addJavaDocLine(" * " + introspectedColumn.getRemarks());
                field.addJavaDocLine(" */");
            }
        } else {
            field.addJavaDocLine("/**");
            field.addJavaDocLine(" * This field was generated by MyBatis Generator.");
            field.addJavaDocLine(" * This field corresponds to the database column " + introspectedTable.getTableConfiguration().getTableName() + "." + introspectedColumn.getActualColumnName() + "");
            field.addJavaDocLine(" *");
            field.addJavaDocLine(" * @mbggenerated");
            field.addJavaDocLine(" */");
        }

        if (isAnnotations) {
            boolean isId = false;
            for (IntrospectedColumn column : introspectedTable.getPrimaryKeyColumns()) {
                if (introspectedColumn == column) {
                    isId = true;
                    field.addAnnotation("@Id");
                    field.addAnnotation("@GeneratedValue");
                    break;
                }
            }
            if (!introspectedColumn.isNullable() && !isId) {
                field.addAnnotation("@NotEmpty");
            }
            Optional<GeneratedKey> optional = introspectedTable.getTableConfiguration().getGeneratedKey();
            String runtimeSqlStatement = optional.isPresent() ? optional.get().getRuntimeSqlStatement() : null;

            if (introspectedColumn.isIdentity()) {
                if ("JDBC".equals(runtimeSqlStatement)) {
                    field.addAnnotation("@GeneratedValue(generator = \"JDBC\")");
                } else {
                    field.addAnnotation("@GeneratedValue(strategy = GenerationType.IDENTITY)");
                }
            } else if (introspectedColumn.isSequenceColumn()) {
                field.addAnnotation("@SequenceGenerator(name=\"\",sequenceName=\"" + runtimeSqlStatement + "\")");
            }
        }
    }

    @Override
    public void addFieldComment(Field field, IntrospectedTable introspectedTable) {
        if (!columnRemarks) {
            field.addJavaDocLine("/**");
            field.addJavaDocLine(" * This field was generated by MyBatis Generator.");
            field.addJavaDocLine(" * This field corresponds to the database table " + introspectedTable.getTableConfiguration().getTableName());
            field.addJavaDocLine(" *");
            field.addJavaDocLine(" * @mbggenerated");
            field.addJavaDocLine(" */");
        }
    }

    @Override
    public void addGeneralMethodComment(Method method, IntrospectedTable introspectedTable) {
        if (!columnRemarks) {
            method.addJavaDocLine("/**");
            method.addJavaDocLine(" * This method was generated by MyBatis Generator.");
            method.addJavaDocLine(" * This method corresponds to the database table " + introspectedTable.getTableConfiguration().getTableName());
            method.addJavaDocLine(" *");
            method.addJavaDocLine(" * @mbggenerated");
            method.addJavaDocLine(" */");
        }
    }

    @Override
    public void addGetterComment(Method method, IntrospectedTable introspectedTable, IntrospectedColumn introspectedColumn) {
        if (!columnRemarks) {
            method.addJavaDocLine("/**");
            method.addJavaDocLine(" * This method was generated by MyBatis Generator.");
            method.addJavaDocLine(" * This method returns the value of the database column " + introspectedTable.getTableConfiguration().getTableName() + "." + introspectedColumn.getActualColumnName() + "");
            method.addJavaDocLine(" *");
            method.addJavaDocLine(" * @return the value of " + introspectedTable.getTableConfiguration().getTableName() + "." + introspectedColumn.getActualColumnName());
            method.addJavaDocLine(" *");
            method.addJavaDocLine(" * @mbggenerated");
            method.addJavaDocLine(" */");
        }
    }

    @Override
    public void addSetterComment(Method method, IntrospectedTable introspectedTable, IntrospectedColumn introspectedColumn) {
        if (!columnRemarks) {
            method.addJavaDocLine("/**");
            method.addJavaDocLine(" * This method was generated by MyBatis Generator.");
            method.addJavaDocLine(" * This method sets the value of the database column " + introspectedTable.getTableConfiguration().getTableName() + "." + introspectedColumn.getActualColumnName() + "");
            method.addJavaDocLine(" *");
            method.addJavaDocLine(" * @param " + method.getParameters().get(0).getName() + " the value for " + introspectedTable.getTableConfiguration().getTableName() + "." + introspectedColumn.getActualColumnName());
            method.addJavaDocLine(" *");
            method.addJavaDocLine(" * @mbggenerated");
            method.addJavaDocLine(" */");
        }
    }

    @Override
    public void addClassComment(InnerClass innerClass, IntrospectedTable introspectedTable, boolean markAsDoNotDelete) {
        if (!columnRemarks) {
            innerClass.addJavaDocLine("/**");
            innerClass.addJavaDocLine(" * This class was generated by MyBatis Generator.");
            innerClass.addJavaDocLine(" * This class corresponds to the database table " + introspectedTable.getTableConfiguration().getTableName());
            innerClass.addJavaDocLine(" *");
            innerClass.addJavaDocLine(" * @mbggenerated do_not_delete_during_merge");
            innerClass.addJavaDocLine(" */");
        }
    }
}
